---
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.5.1

before_install: gem install bundler -v 1.16.5

script:
  - bundle exec bundle-audit
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec rake yard:junk
